name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: mod_process_security ${{ github.ref }}
          draft: false
          prerelease: false

  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - centos-7
          - almalinux-8
          - almalinux-9

    env:
      BUILD_IMAGE: ${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build RPM
        id: build_rpm
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed -e 's|refs/tags/||g')
          ./redhat/build -t "${TAG_NAME}" "${BUILD_IMAGE/-/:}"
          echo "##[set-output name=release-tag;]${TAG_NAME}"
      - name: Upload Assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "redhat/rpmbuild/RPMS/x86_64/*.rpm;redhat/rpmbuild/SRPMS/*.rpm"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.build_rpm.outputs.release-tag }}

