name: test

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      max-parallel: 20
      matrix:
        image:
          - almalinux-8
          - almalinux-9
          - almalinux-10

    env:
      BUILD_IMAGE: ${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build RPM
        id: build_rpm
        run: |
          ./redhat/build -t "${GITHUB_SHA}" "${BUILD_IMAGE/-/:}"

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.image }}
          path: redhat/rpmbuild/**/*.rpm

